[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
grpcx = { version = "0.1.0", path = "../../grpcx" }
structopt = "0.3.26"
tokio = { version = "1.45.0", features = ["rt-multi-thread"] }
